# Generated by Django 4.2.7 on 2025-01-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
